// wdfldr.cpp — Windows Driver Framework Loader handler (STUB)
#include "wdfldr.h"

namespace speakeasy { namespace api { namespace kernelmode {

Wdfldr::Wdfldr() {
    INIT_API_TABLE(Wdfldr)
    REG(Wdfldr, WdfVersionBind, 4)
    REG(Wdfldr, WdfDriverCreate, 6)
    REG(Wdfldr, WdfDeviceInitSetPnpPowerEventCallbacks, 3)
    REG(Wdfldr, WdfDeviceInitSetRequestAttributes, 3)
    REG(Wdfldr, WdfDeviceInitSetFileObjectConfig, 4)
    REG(Wdfldr, WdfDeviceInitSetIoType, 3)
    REG(Wdfldr, WdfDeviceCreate, 4)
    REG(Wdfldr, WdfObjectGetTypedContextWorker, 3)
    REG(Wdfldr, WdfDriverOpenParametersRegistryKey, 5)
    REG(Wdfldr, WdfRegistryQueryULong, 4)
    REG(Wdfldr, WdfRegistryClose, 2)
    REG(Wdfldr, WdfDeviceSetPnpCapabilities, 3)
    REG(Wdfldr, WdfIoQueueReadyNotify, 4)
    REG(Wdfldr, WdfDeviceCreateDeviceInterface, 4)
    REG(Wdfldr, WdfIoQueueCreate, 5)
    REG(Wdfldr, WdfDeviceWdmGetAttachedDevice, 2)
    REG(Wdfldr, WdfDeviceWdmGetDeviceObject, 2)
    REG(Wdfldr, WdfUsbTargetDeviceCreateWithParameters, 5)
    REG(Wdfldr, WdfUsbTargetDeviceGetDeviceDescriptor, 3)
    REG(Wdfldr, WdfMemoryCreate, 7)
    REG(Wdfldr, WdfUsbTargetDeviceSelectConfig, 4)
    REG(Wdfldr, WdfUsbTargetDeviceRetrieveConfigDescriptor, 4)
    REG(Wdfldr, WdfUsbInterfaceSelectSetting, 4)
    REG(Wdfldr, WdfUsbTargetDeviceGetNumInterfaces, 2)
    REG(Wdfldr, WdfUsbInterfaceGetNumConfiguredPipes, 2)
    REG(Wdfldr, WdfUsbInterfaceGetNumSettings, 2)
    REG(Wdfldr, WdfUsbTargetDeviceRetrieveInformation, 3)
    REG(Wdfldr, WdfUsbInterfaceGetConfiguredPipe, 4)
    REG(Wdfldr, WdfUsbTargetPipeGetInformation, 3)
    REG(Wdfldr, WdfUsbInterfaceGetInterfaceNumber, 2)
    END_API_TABLE
}

#define WL_STUB(n) KERNEL_STUB(Wdfldr, n)
WL_STUB(WdfVersionBind)
WL_STUB(WdfDriverCreate)
WL_STUB(WdfDeviceInitSetPnpPowerEventCallbacks)
WL_STUB(WdfDeviceInitSetRequestAttributes)
WL_STUB(WdfDeviceInitSetFileObjectConfig)
WL_STUB(WdfDeviceInitSetIoType)
WL_STUB(WdfDeviceCreate)
WL_STUB(WdfObjectGetTypedContextWorker)
WL_STUB(WdfDriverOpenParametersRegistryKey)
WL_STUB(WdfRegistryQueryULong)
WL_STUB(WdfRegistryClose)
WL_STUB(WdfDeviceSetPnpCapabilities)
WL_STUB(WdfIoQueueReadyNotify)
WL_STUB(WdfDeviceCreateDeviceInterface)
WL_STUB(WdfIoQueueCreate)
WL_STUB(WdfDeviceWdmGetAttachedDevice)
WL_STUB(WdfDeviceWdmGetDeviceObject)
WL_STUB(WdfUsbTargetDeviceCreateWithParameters)
WL_STUB(WdfUsbTargetDeviceGetDeviceDescriptor)
WL_STUB(WdfMemoryCreate)
WL_STUB(WdfUsbTargetDeviceSelectConfig)
WL_STUB(WdfUsbTargetDeviceRetrieveConfigDescriptor)
WL_STUB(WdfUsbInterfaceSelectSetting)
WL_STUB(WdfUsbTargetDeviceGetNumInterfaces)
WL_STUB(WdfUsbInterfaceGetNumConfiguredPipes)
WL_STUB(WdfUsbInterfaceGetNumSettings)
WL_STUB(WdfUsbTargetDeviceRetrieveInformation)
WL_STUB(WdfUsbInterfaceGetConfiguredPipe)
WL_STUB(WdfUsbTargetPipeGetInformation)
WL_STUB(WdfUsbInterfaceGetInterfaceNumber)

}}} // namespaces
