// iphlpapi.cpp — iphlpapi.dll handler (v2 — stubs)
#include "iphlpapi.h"

namespace speakeasy { namespace api {

Iphlpapi::Iphlpapi() {
    INIT_API_TABLE(Iphlpapi)
    REG(Iphlpapi, GetAdaptersInfo, 2)
    REG(Iphlpapi, GetAdaptersAddresses, 5)
    REG(Iphlpapi, GetIfEntry, 2)
    REG(Iphlpapi, GetIfTable, 3)
    REG(Iphlpapi, GetExtendedTcpTable, 6)
    REG(Iphlpapi, GetExtendedUdpTable, 6)
    REG(Iphlpapi, GetNetworkParams, 2)
    REG(Iphlpapi, GetBestInterface, 2)
    REG(Iphlpapi, GetBestRoute, 3)
    REG(Iphlpapi, GetRTTAndHopCount, 4)
    REG(Iphlpapi, GetFriendlyIfIndex, 1)
    REG(Iphlpapi, NotifyAddrChange, 2)
    REG(Iphlpapi, NotifyRouteChange, 2)
    REG(Iphlpapi, CancelIPChangeNotify, 1)
    REG(Iphlpapi, FlushIpNetTable, 2)
    REG(Iphlpapi, FlushIpPathTable, 1)
    REG(Iphlpapi, GetIpAddrTable, 3)
    REG(Iphlpapi, GetIpForwardTable, 3)
    REG(Iphlpapi, GetIpNetTable, 3)
    REG(Iphlpapi, GetIpStatistics, 1)
    REG(Iphlpapi, GetIpStatisticsEx, 2)
    REG(Iphlpapi, GetTcpStatistics, 1)
    REG(Iphlpapi, GetTcpStatisticsEx, 2)
    REG(Iphlpapi, GetUdpStatistics, 1)
    REG(Iphlpapi, GetUdpStatisticsEx, 2)
    REG(Iphlpapi, SetIpStatistics, 1)
    REG(Iphlpapi, SetIpTTL, 1)
    REG(Iphlpapi, AllocateAndGetIpAddrTableFromStack, 4)
    REG(Iphlpapi, AllocateAndGetIpNetTableFromStack, 4)
    REG(Iphlpapi, AllocateAndGetTcpTableFromStack, 4)
    REG(Iphlpapi, AllocateAndGetUdpTableFromStack, 4)
    REG(Iphlpapi, GetInterfaceInfo, 2)
    REG(Iphlpapi, GetNumberOfInterfaces, 1)
    REG(Iphlpapi, DhcpRequestParams, 7)
    REG(Iphlpapi, EnableRouter, 3)
    REG(Iphlpapi, UnenableRouter, 2)
    REG(Iphlpapi, IpReleaseAddress, 2)
    REG(Iphlpapi, IpRenewAddress, 2)
    REG(Iphlpapi, SendARP, 4)
    REG(Iphlpapi, Ping, 6)
    REG(Iphlpapi, PingEx, 7)
    REG(Iphlpapi, CancelIPInfoChange, 1)
    REG(Iphlpapi, SetAdapterIpAddress, 3)
    REG(Iphlpapi, AddIPAddress, 5)
    REG(Iphlpapi, DeleteIPAddress, 2)
    END_API_TABLE
}

// ── Bulk stubs ──────────────────────────────────────────────

#define IPH_STUB(n) STUB(Iphlpapi, n)

IPH_STUB(GetAdaptersInfo)
IPH_STUB(GetAdaptersAddresses)
IPH_STUB(GetIfEntry)
IPH_STUB(GetIfTable)
IPH_STUB(GetExtendedTcpTable)
IPH_STUB(GetExtendedUdpTable)
IPH_STUB(GetNetworkParams)
IPH_STUB(GetBestInterface)
IPH_STUB(GetBestRoute)
IPH_STUB(GetRTTAndHopCount)
IPH_STUB(GetFriendlyIfIndex)
IPH_STUB(NotifyAddrChange)
IPH_STUB(NotifyRouteChange)
IPH_STUB(CancelIPChangeNotify)
IPH_STUB(FlushIpNetTable)
IPH_STUB(FlushIpPathTable)
IPH_STUB(GetIpAddrTable)
IPH_STUB(GetIpForwardTable)
IPH_STUB(GetIpNetTable)
IPH_STUB(GetIpStatistics)
IPH_STUB(GetIpStatisticsEx)
IPH_STUB(GetTcpStatistics)
IPH_STUB(GetTcpStatisticsEx)
IPH_STUB(GetUdpStatistics)
IPH_STUB(GetUdpStatisticsEx)
IPH_STUB(SetIpStatistics)
IPH_STUB(SetIpTTL)
IPH_STUB(AllocateAndGetIpAddrTableFromStack)
IPH_STUB(AllocateAndGetIpNetTableFromStack)
IPH_STUB(AllocateAndGetTcpTableFromStack)
IPH_STUB(AllocateAndGetUdpTableFromStack)
IPH_STUB(GetInterfaceInfo)
IPH_STUB(GetNumberOfInterfaces)
IPH_STUB(DhcpRequestParams)
IPH_STUB(EnableRouter)
IPH_STUB(UnenableRouter)
IPH_STUB(IpReleaseAddress)
IPH_STUB(IpRenewAddress)
IPH_STUB(SendARP)
IPH_STUB(Ping)
IPH_STUB(PingEx)
IPH_STUB(CancelIPInfoChange)
IPH_STUB(SetAdapterIpAddress)
IPH_STUB(AddIPAddress)
IPH_STUB(DeleteIPAddress)

}} // namespaces
