// netapi32.cpp — netapi32.dll handler (v2 — stubs)
#include "netapi32.h"

namespace speakeasy { namespace api {

NetApi32::NetApi32() {
    INIT_API_TABLE(NetApi32)
    REG(NetApi32, NetGetJoinInformation, 3)
    REG(NetApi32, NetWkstaGetInfo, 3)
    REG(NetApi32, NetWkstaUserEnum, 4)
    REG(NetApi32, NetServerEnum, 8)
    REG(NetApi32, NetServerEnumEx, 8)
    REG(NetApi32, NetServerGetInfo, 3)
    REG(NetApi32, NetServerSetInfo, 4)
    REG(NetApi32, NetUserAdd, 4)
    REG(NetApi32, NetUserDel, 3)
    REG(NetApi32, NetUserEnum, 8)
    REG(NetApi32, NetUserGetGroups, 4)
    REG(NetApi32, NetUserGetInfo, 4)
    REG(NetApi32, NetUserSetInfo, 5)
    REG(NetApi32, NetUserGetLocalGroups, 7)
    REG(NetApi32, NetUserModalsGet, 3)
    REG(NetApi32, NetUserModalsSet, 4)
    REG(NetApi32, NetGroupEnum, 8)
    REG(NetApi32, NetGroupGetInfo, 4)
    REG(NetApi32, NetGroupSetInfo, 5)
    REG(NetApi32, NetGroupAddUser, 3)
    REG(NetApi32, NetGroupDelUser, 3)
    REG(NetApi32, NetLocalGroupEnum, 7)
    REG(NetApi32, NetLocalGroupGetInfo, 4)
    REG(NetApi32, NetLocalGroupSetInfo, 5)
    REG(NetApi32, NetLocalGroupAdd, 4)
    REG(NetApi32, NetLocalGroupAddMembers, 6)
    REG(NetApi32, NetLocalGroupDelMembers, 6)
    REG(NetApi32, NetLocalGroupGetMembers, 7)
    REG(NetApi32, NetApiBufferAllocate, 2)
    REG(NetApi32, NetApiBufferFree, 1)
    REG(NetApi32, NetApiBufferReallocate, 3)
    REG(NetApi32, NetApiBufferSize, 2)
    REG(NetApi32, NetGetDCName, 3)
    REG(NetApi32, NetGetAnyDCName, 3)
    REG(NetApi32, NetGetDisplayInformationIndex, 5)
    REG(NetApi32, NetQueryDisplayInformation, 8)
    REG(NetApi32, NetShareAdd, 4)
    REG(NetApi32, NetShareCheck, 3)
    REG(NetApi32, NetShareDel, 3)
    REG(NetApi32, NetShareEnum, 8)
    REG(NetApi32, NetShareGetInfo, 4)
    REG(NetApi32, NetShareSetInfo, 5)
    REG(NetApi32, NetConnectionEnum, 8)
    REG(NetApi32, NetFileEnum, 8)
    REG(NetApi32, NetFileGetInfo, 4)
    REG(NetApi32, NetFileClose, 2)
    REG(NetApi32, NetSessionEnum, 8)
    REG(NetApi32, NetSessionGetInfo, 4)
    REG(NetApi32, NetSessionDel, 3)
    REG(NetApi32, NetUseAdd, 4)
    REG(NetApi32, NetUseDel, 3)
    REG(NetApi32, NetUseEnum, 8)
    REG(NetApi32, NetUseGetInfo, 4)
    REG(NetApi32, NetScheduleJobAdd, 3)
    REG(NetApi32, NetScheduleJobDel, 3)
    REG(NetApi32, NetScheduleJobEnum, 5)
    REG(NetApi32, NetScheduleJobGetInfo, 4)
    REG(NetApi32, NetRemoteComputerSupports, 2)
    REG(NetApi32, NetRemoteTOD, 2)
    REG(NetApi32, NetWkstaSetInfo, 4)
    REG(NetApi32, NetWkstaTransportEnum, 5)
    REG(NetApi32, NetWkstaTransportAdd, 4)
    REG(NetApi32, NetWkstaTransportDel, 3)
    REG(NetApi32, NetAccessAdd, 4)
    REG(NetApi32, NetAccessDel, 3)
    REG(NetApi32, NetAccessEnum, 8)
    REG(NetApi32, NetAccessGetInfo, 4)
    REG(NetApi32, NetAccessSetInfo, 5)
    REG(NetApi32, NetAuditClear, 2)
    REG(NetApi32, NetAuditRead, 10)
    REG(NetApi32, NetAuditWrite, 4)
    REG(NetApi32, NetConfigGet, 4)
    REG(NetApi32, NetConfigGetAll, 3)
    REG(NetApi32, NetConfigSet, 5)
    REG(NetApi32, NetErrorLogClear, 2)
    REG(NetApi32, NetErrorLogRead, 10)
    REG(NetApi32, NetErrorLogWrite, 8)
    REG(NetApi32, SetServiceBits, 3)
    END_API_TABLE
}

// ── Bulk stubs ──────────────────────────────────────────────

#define NET_STUB(n) STUB(NetApi32, n)

NET_STUB(NetGetJoinInformation)
NET_STUB(NetWkstaGetInfo)
NET_STUB(NetWkstaUserEnum)
NET_STUB(NetServerEnum)
NET_STUB(NetServerEnumEx)
NET_STUB(NetServerGetInfo)
NET_STUB(NetServerSetInfo)
NET_STUB(NetUserAdd)
NET_STUB(NetUserDel)
NET_STUB(NetUserEnum)
NET_STUB(NetUserGetGroups)
NET_STUB(NetUserGetInfo)
NET_STUB(NetUserSetInfo)
NET_STUB(NetUserGetLocalGroups)
NET_STUB(NetUserModalsGet)
NET_STUB(NetUserModalsSet)
NET_STUB(NetGroupEnum)
NET_STUB(NetGroupGetInfo)
NET_STUB(NetGroupSetInfo)
NET_STUB(NetGroupAddUser)
NET_STUB(NetGroupDelUser)
NET_STUB(NetLocalGroupEnum)
NET_STUB(NetLocalGroupGetInfo)
NET_STUB(NetLocalGroupSetInfo)
NET_STUB(NetLocalGroupAdd)
NET_STUB(NetLocalGroupAddMembers)
NET_STUB(NetLocalGroupDelMembers)
NET_STUB(NetLocalGroupGetMembers)
NET_STUB(NetApiBufferAllocate)
NET_STUB(NetApiBufferFree)
NET_STUB(NetApiBufferReallocate)
NET_STUB(NetApiBufferSize)
NET_STUB(NetGetDCName)
NET_STUB(NetGetAnyDCName)
NET_STUB(NetGetDisplayInformationIndex)
NET_STUB(NetQueryDisplayInformation)
NET_STUB(NetShareAdd)
NET_STUB(NetShareCheck)
NET_STUB(NetShareDel)
NET_STUB(NetShareEnum)
NET_STUB(NetShareGetInfo)
NET_STUB(NetShareSetInfo)
NET_STUB(NetConnectionEnum)
NET_STUB(NetFileEnum)
NET_STUB(NetFileGetInfo)
NET_STUB(NetFileClose)
NET_STUB(NetSessionEnum)
NET_STUB(NetSessionGetInfo)
NET_STUB(NetSessionDel)
NET_STUB(NetUseAdd)
NET_STUB(NetUseDel)
NET_STUB(NetUseEnum)
NET_STUB(NetUseGetInfo)
NET_STUB(NetScheduleJobAdd)
NET_STUB(NetScheduleJobDel)
NET_STUB(NetScheduleJobEnum)
NET_STUB(NetScheduleJobGetInfo)
NET_STUB(NetRemoteComputerSupports)
NET_STUB(NetRemoteTOD)
NET_STUB(NetWkstaSetInfo)
NET_STUB(NetWkstaTransportEnum)
NET_STUB(NetWkstaTransportAdd)
NET_STUB(NetWkstaTransportDel)
NET_STUB(NetAccessAdd)
NET_STUB(NetAccessDel)
NET_STUB(NetAccessEnum)
NET_STUB(NetAccessGetInfo)
NET_STUB(NetAccessSetInfo)
NET_STUB(NetAuditClear)
NET_STUB(NetAuditRead)
NET_STUB(NetAuditWrite)
NET_STUB(NetConfigGet)
NET_STUB(NetConfigGetAll)
NET_STUB(NetConfigSet)
NET_STUB(NetErrorLogClear)
NET_STUB(NetErrorLogRead)
NET_STUB(NetErrorLogWrite)
NET_STUB(SetServiceBits)

}} // namespaces
